PR : Faz2 General Fixes
anilhazar/hr-be-api pull request #20
Opened 2024-05-11 08:32 UTC by anilhazar

2024-05-20 13:11 UTC, agitrubard requested changes

2024-05-20 13:11 UTC, agitrubard commented on pom.xml
> +			<version>6.1.4</version>
Versiyon kontrollerini kolay bir şekilde yapabilmek için versiyonu `pom.xml` içerisindeki properties kısmına tanımlayabilirsin

2024-05-20 13:11 UTC, agitrubard commented on src/main/resources/sql/hr-be-api.sql
>      request_type ENUM ('BIRTH', 'ANNUAL', 'PATERNITY', 'EXCUSE') NOT NULL,
```suggestion
    type ENUM ('BIRTH', 'ANNUAL', 'PATERNITY', 'EXCUSE') NOT NULL,
```

2024-05-20 13:38 UTC, anilhazar commented on pom.xml
> +			<version>6.1.4</version>
Geliştirme yapıldı

2024-05-20 14:26 UTC, agitrubard requested changes

2024-05-20 14:26 UTC, agitrubard commented on pom.xml
>          <mysql.connector.version>8.3.0</mysql.connector.version>
Bu dosyanın formatında problem var sanırım

2024-05-20 14:26 UTC, agitrubard commented on src/main/java/com/spring/model/dto/request/EmployeeCreateRequest.java
>      private int age;
```suggestion
    private Integer age;
```

2024-05-20 14:26 UTC, agitrubard commented on src/main/java/com/spring/model/dto/response/LeaveRequestResponse.java
> +    private final RequestStatus requestStatus;
```suggestion
    private final RequestStatus status;
```

2024-05-20 14:26 UTC, agitrubard commented on src/main/java/com/spring/service/impl/EmployeeEmailServiceImpl.java
> +    public void sendBirthdayEmail() {
Bu metot burada olmasa daha iyi olabilir ve public yaptığın için diğer yerlerden çağrılabiliyor, buna dikkat etmek lazım

2024-05-20 14:26 UTC, agitrubard commented on src/main/resources/sql/hr-be-api.sql
> +
Burada bir database şifresi verip bir şema oluşturmak lazım, bu şemanın application.yml'daki default verilerle çalışabiliyor olması lazım

2024-05-20 20:26 UTC, anilhazar commented on pom.xml
>          <mysql.connector.version>8.3.0</mysql.connector.version>
kontrol ettim bir sorun görünmüyor

2024-05-20 20:26 UTC, anilhazar commented on src/main/java/com/spring/model/dto/request/EmployeeCreateRequest.java
>      private int age;
Done

2024-05-20 20:28 UTC, anilhazar commented on src/main/java/com/spring/service/impl/EmployeeEmailServiceImpl.java
> +    public void sendBirthdayEmail() {
Access modifier düzeltildi. Employee Email service sınıfı, bu metodun yaptığı işe uygun diye düşünüyorum.

2024-05-20 20:30 UTC, anilhazar commented on src/main/resources/sql/hr-be-api.sql
> +
gerekli düzenlemeler yapıldı

2024-05-22 09:33 UTC, agitrubard commented on src/main/resources/application.yml
> +    password: ${db.password:password}
Buradaki `name` ve `password` ile veri tabanına bağlanılabiliyor mu?

2024-05-22 19:16 UTC, merged